name: angular_tour_of_heroes
description: A web app that uses AngularDart Components
# version: 1.0.0
# author: Anton <6088046+ntnbrtnkv@users.noreply.github.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  angular: ^5.3.0
  angular_router: ^2.0.0-alpha
  angular_forms: ^2.0.0
  angular_components: ^0.13.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  dart_style: ^1.2.0
  pedantic: ^1.7.0
  test: ^1.6.0
